const ResponseMessage = {
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  BAD_REQUEST: "Bad request",
  USER_CREATED: "User sign up successfully",
  USER_ALREADY_EXIST: "User already exist",
  USER_LOGIN: "User logged in successfully",
  TOKEN_REQUIRED: "Token is required for authentication",
  NOT_AUTHORIZE: "Token not authorized",
  PASSWORD_NOT_MATCH: "Password not match",
  DATA_NOT_FOUND: "Data not found",
  DATA_FOUND: "List fetched successfully",
  ALL_FIELDS_REQUIRES: "All fields required",
  USER_NOT_FOUND: "User not found",
  CHAT_PINNED: "Chat pinned successfully",
  USER_UPDATED: "User updated successfully",
  USER_DELETED: "User deleted successfully",
  USER_ACTIVE: "User activated successfully",
  USER_DEACTIVE: "User deactivated successfully",
  CAPSULE_CREATED:
    "Capsule created successfully. It will be published after verification.",
  CAPSULE_NOT_CREATED: "Capsule creation failed. Please try again.",
  CAPSULE_VERIFIED: "Capsule verified successfully",
  CAPSULE_UNVERIFIED: "Capsule unverified successfully",
  CAPSULE_ACTIVATED: "Capsule activated successfully",
  CAPSULE_DEACTIVATED: "Capsule deactivated successfully",
  CAPUSLE_DELETED: "Capsule deleted successfully",
  DATA_NOT_FOUND: "Data not found",
};

export default ResponseMessage;
